name: Azure Web App Node Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  actions: read

env:
  AZURE_WEBAPP_NAME: coders-cup-24-frontend
  AZURE_WEBAPP_PACKAGE_PATH: 'dist'
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'npm install, build, and test'
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: 'Copy web.config to dist'
        run: |
          cp web.config dist/

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: 'Logout from Azure'
        run: |
          az logout
